name: LetopisDungeon
version: 0.2.0
main: ru.letopis.dungeon.LetopisDungeonPlugin
api-version: "1.21"
author: ATMOS
description: Кооперативный данж с волнами, головоломкой и финальным боссом.
commands:
  letodungeon:
    description: Команды LetopisDungeon
    usage: /letodungeon
permissions:
  letodungeon.use:
    default: true
  letodungeon.admin:
    default: op
  letodungeon.debug:
    default: op
