name: LetopisDungeon
version: 0.1.0
main: ru.letopis.dungeon.LetopisDungeonPlugin
api-version: "1.21"
author: ATMOS
description: Session dungeon with director (50/50 combat/puzzles) in separate world.
commands:
  letodungeon:
    description: LetopisDungeon commands
    usage: /letodungeon
permissions:
  letodungeon.use:
    default: true
  letodungeon.admin:
    default: op
