# Определяет, будет ли использоваться MySQL. По умолчанию EliteMobs использует SQLite. Для MySQL нужен корректный конфиг.
useMySQL: false
# Хост вашей базы MySQL.
mysqlHost: localhost
# Порт вашей базы MySQL.
mysqlPort: '3306'
# Имя базы данных.
mysqlDatabaseName: elitemobs
# Имя пользователя для MySQL.
mysqlUsername: your_username_mysql_here
# Пароль для вашей базы MySQL.
mysqlPassword: your_mysql_password_here
# Использовать ли SSL.
useSSL: true
